server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

spring:
  application:
    name: observer-monitor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/observer?useUnicode=true&character=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 5264
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 50000

mybatis-plus:
  type-aliases-package: com.future.observermonitor.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl